# Content configuration version
version: 2

# Personal info
name: Sebastien Coll
title: Systems Software Developer
email: scoll010@uottawa.ca
website: https://sebastiencoll.github.io/

# Dark Mode (true/false/never)
darkmode: false

# Social links
linkedin_username: sébastiencoll
# About Section
# about_title: About Me
about_profile_image: images/1654479118511.jpg
about_content: | # this will include new lines to allow paragraphs
  My name is Sebastien Coll and I am a 2024 Computer Engineering graduate (University of Ottawa). I have experience full stack web development, mobile development, embedded systems, test automation and tooling. I have worked at a number of companies gaining teamwork and leadership skills.

content:
  - title: Projects
    layout: list
    content:
      - layout: top-middle
        title: Sippe
        quote: >
          React Native, Firebase Suite, GCP, Stripe
        description: |
          Mobile application for streamlined food and drinks ordering, specialized in events. I learned a lot about how to make a mobile app from scratch and how to deal with real time changes to make it a seemless experience for the user.
      - layout: top-middle
        title: Agriculture robot
        quote: >
          Arduino, Raspberry Pi, C, Python, React Native, Firebase Suite
        description: |
          Mobile-controlled/autonomous robot with multiple sensors and motors used to gather information of a garden or agricultural lands. Great learning experience for robotics, embedded systems, and mobile app development.

      - layout: top-middle
        title: Gamekeeper WebApp
        quote: >
          React
        description: |
          Web application used by scorekeepers in the Ottawa/Gatineau Region to mark hockey games in real time. Built in pure React, this project was a great way to learn how to make a web app from scratch. I learned a lot about user experience and how to make an application simple to use. It is still in use today.

      - layout: top-middle
        title: Garden web store
        quote: >
          React, MongoDB, Express, Node.js (MERN)
        description: | # this will include new lines to allow paragraphs
          Simple web store for nurseries to sell their products. First project I made using the MERN stack. I learned a lot about how to make a full stack web app. I also learned a lot about how to make a good looking website and how to make it user friendly.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Ford Motor Company
        sub_title: Systems Software Developer (Kanata, Ontario)
        caption: January 2023 - Present
        description: |
          Develop, support and maintain gRPC, SOME/IP and CAN tools (Python, SOMEIP, ARXML, gRPC, protobuf) <br>
          Test suites support and automation for embedded systems <br>
          TCU development (Python, Linux, TCP, UDP) <br>
          Create multiple tools and reports to support developers and team leaders (Python)
      - layout: left
        title: Ford Motor Company
        sub_title: Systems Software Intern (Kanata, Ontario)
        caption: May 2022 - September 2022
        description: |
          Maintain test suites and automate them to run on hardware <br>
          Platform and tooling (Python, Jenkins, GIT) <br>
          TCU development, test and automation <br>
      - layout: left
        title: Cisco Systems Canada
        sub_title: Technical Intern (Kanata, Ontario)
        caption: September 2021 - December 2021
        description: |
          Develop and support the company's test automation framework (Python, Jenkins, GIT) <br>
          Add automation scripts to already existing test features <br>
          Automate of multiple nightly tests runs with code coverage <br>
      - layout: left
        title: Motorola Solutions Inc.
        sub_title: Full Stack Software COOP (Gatineau, Quebec)
        caption: January 2021 - May 2021
        description: |
          Revamped a web application using NodeJS, PostgreSQL, Angular, Express, Supertest and Jest <br>
          Presented work to managers, product owners, stakeholders, and R&D teams. <br>

  - title: Education
    layout: list
    content:
      - layout: left
        title: University of Ottawa
        caption: 2019 - 2024
        sub_title: BSc Computer Engineering
# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag
